language: node_js
node_js:
- 0.12

#dependencies for before.js
install:
- npm install cheerio
- npm install moment

before_script:
    - node travis_scripts/before.js

script:
    - bash ./travis_scripts/build.sh
    - bash ./travis_scripts/deploy.sh

#deploy:
#  provider: script
#  script:
#  on:
#    branch: master

#for gh-pages deployment. https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
env:
    global:
      - ENCRYPTION_LABEL: "bfabfa4a3ae4"
      - COMMIT_AUTHOR_EMAIL: "travis@example.com"
